### ISSUE TITLE
Why confidence is bigger than 1

### ISSUE THREAD

**Issue by ErrorontheError** [flutter-ml/mlkit-custom-model#1]
I am using the demo and it shows confidence greater than 1 for example IMAGE LABELER: labeler response: daisy confidence: 8.07. How to train the model so that the confidence is in the range [0,1]. I need to  show my result in percent so confiedence must be in range [0,1]. Please help me. Update the model.py.  I have one more question: When do you custom object detection model for google colab?

**Comment by fbernaly** [comment]
I created the google colab to make it as a tutorial, but you can download this [file](https://github.com/flutter-ml/mlkit-custom-model/blob/main/ml_kit_custom_model.py) tweak it and train your own model in your local machine

**Comment by ErrorontheError** [comment]
ok but I mean something else. I need custom object detection model not custom classification model. And please answer why confidence is bigger than 1 in your flutter expamle
